repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v3.4.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-ast
  - repo: 'https://github.com/psf/black'
    rev: 20.8b1
    hooks:
      - id: black
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
          - flake8-quotes
        args:
          - '--ignore=W503,Q003,E203,T001,E722'
          - '--max-line-length=120'
          - '--inline-quotes=double'
