---
# SPDX-License-Identifier: GPL-3.0-or-later

providers:
    '91':
        - name: confirmtkt
          method: GET
          url: https://securedapi.confirmtkt.com/api/platform/register
          params:
              newOtp: 'true'
              mobile_number: '{target}'
          identifier: 'false'
        - name: justdial
          method: GET
          url: https://t.justdial.com/api/india_api_write/18july2018/sendvcode.php
          params:
              mobile: '{target}'
          identifier: sent
        - name: myupchar
          method: GET
          url: https://www.myupchar.com/consultation/store_otp
          headers:
              User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
              Accept: '*/*'
              Accept-Language: en-US,en;q=0.5
              X-CSRF-Token: PVsJG4MoiKTLl7RA2KLYzXVoSt2s2URRSlCV3ADvm6M=
              X-Requested-With: XMLHttpRequest
              Connection: keep-alive
              Referer: https://www.myupchar.com/consultation/query
              DNT: '1'
          params:
              phone: '{target}'
          identifier: आपके मोबाइल नंबर पर OTP भेज दिया गया है।
        - name: frotels
          method: POST
          url: https://www.frotels.com/appsendsms.php
          data:
              mobno: '{target}'
          identifier: sent
        - name: gapoon
          method: POST
          url: https://www.gapoon.com/userSignup
          data:
              mobile: '{target}'
              email: a@a.com
              name: a
          identifier: '1'
        - name: housing
          method: POST
          url: https://login.housing.com/api/v2/send-otp
          data_type: json
          data:
              phone: '{target}'
          identifier: Sent
        - name: porter
          method: POST
          url: https://porter.in/restservice/send_app_link_sms
          data:
              phone: '{target}'
              referrer_string: ''
              brand: porter
          identifier: 'true'
        - name: cityflo
          method: POST
          url: https://cityflo.com/website-app-download-link-sms/
          data:
              mobile_number: '{target}'
          identifier: sent
        - name: nnnow
          method: POST
          url: https://api.nnnow.com/d/api/appDownloadLink
          data:
              mobileNumber: '{target}'
          identifier: 'true'
        - name: ajio
          method: POST
          url: https://login.web.ajio.com/api/auth/signupSendOTP
          data:
              firstName: xxps
              login: wiqpdl223@wqew.com
              password: QASpw@1s
              genderType: Male
              mobileNumber: '{target}'
              requestType: SENDOTP
          identifier: '1'
        - name: happyeasygo
          method: GET
          url: https://www.happyeasygo.com/heg_api/user/sendRegisterOTP.do
          params:
              phone: 91%20{target}
          identifier: 'true'
        - name: unacademy
          method: POST
          url: https://unacademy.com/api/v1/user/get_app_link/
          data_type: json
          data:
              phone: '{target}'
          identifier: sent
        - name: treebo
          method: POST
          url: https://www.treebo.com/api/v2/auth/login/otp/
          data:
              phone_number: '{target}'
          identifier: sent
        - name: mobikwik
          method: POST
          url: https://webapi.mobikwik.com/p/account/otp/cell/v2
          data_type: json
          data:
              cell: '{target}'
          headers:
              X-MClient: '0'
          identifier: 'true'
        - name: airtel
          method: GET
          url: https://www.airtel.in/referral-api/core/notify
          params:
              messageId: map
              rtn: '{target}'
          identifier: Success
        - name: pharmeasy
          method: POST
          url: https://pharmeasy.in/api/auth/requestOTP
          data_type: json
          data:
              contactNumber: '{target}'
          identifier: resendSmsCounter
        - name: mylescars
          method: POST
          url: https://www.mylescars.com/usermanagements/chkContact
          data:
              contactNo: '{target}'
          identifier: 'success@::::'
        - name: grofers
          method: POST
          url: https://grofers.com/v2/accounts/
          data:
              user_phone: '{target}'
          headers:
              auth_key: 3f0b81a721b2c430b145ecb80cfdf51b170bf96135574e7ab7c577d24c45dbd7
          identifier: We have sent
        - name: dream11
          method: POST
          url: https://api.dream11.com/sendsmslink
          data:
              siteId: '1'
              mobileNum: '{target}'
              appType: androidfull
          identifier: 'true'
        - name: cashify
          method: GET
          url: https://www.cashify.in/api/cu01/v1/app-link
          params:
              mn: '{target}'
          identifier: Successfully
        - name: paytm
          method: POST
          url: https://commonfront.paytm.com/v4/api/sendsms
          data_type: json
          data:
              phone: '{target}'
              guid: 2952fa812660c58dc160ca6c9894221d
          identifier: '202'
    multi:
        - name: flipkart
          method: POST
          cc_target: loginId
          url: https://www.flipkart.com/api/5/user/otp/generate
          data:
              loginId: +{target}
          headers:
              X-user-agent: >-
                  Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
                  FKUA/website/41/website/Desktop
              Origin: https://www.flipkart.com
              Content-Type: application/x-www-form-urlencoded
          identifier: emailMask
        - name: qlean
          method: POST
          url: https://qlean.ru/clients-api/v2/sms_codes/auth/request_code
          data:
              phone: '{cc}{target}'
          identifier: request_id
        - name: mail.ru
          method: POST
          url: https://cloud.mail.ru//api/v2/notify/applink
          data_type: json
          data:
              phone: +{cc}{target}
              api: '2'
              email: email
              x-email: x-email
          identifier: '200'
        - name: gotinder
          method: POST
          url: https://api.gotinder.com/v2/auth/sms/send?auth_type=sms&locale=ru
          data:
              phone_number: '{cc}{target}'
          identifier: '200'
        - name: youla.ru
          method: POST
          url: https://youla.ru/web-api/auth/request_code
          data_type: json
          data:
              phone: +{cc}{target}
          identifier: code_length
        - name: ivi.ru
          method: POST
          url: https://api.ivi.ru/mobileapi/user/register/phone/v6
          data:
              phone: '{cc}{target}'
          identifier: 'true'
        - name: delitime.ru
          method: POST
          url: https://api.delitime.ru/api/v2/signup
          data:
              SignupForm[username]: '{cc}{target}'
              SignupForm[device_type]: '3'
          identifier: 'true'
        - name: icq.com
          method: POST
          url: https://www.icq.com/smsreg/requestPhoneValidation.php
          data:
              msisdn: '{cc}{target}'
              locale: en
              k: ic1rtwz1s1Hj1O0r
              r: '45559'
          identifier: '200'
